# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    # - "node_modules/bootstrap-sass/assets/stylesheets"
    - "node_modules/bootstrap/scss"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Библиотеки
    - "node_modules/jquery/dist/jquery.min.js"
    - "node_modules/popper.js/dist/umd/popper.js"
    - "node_modules/bootstrap/dist/js/bootstrap.min.js"

    # Твой код
    - "src/assets/js/!(main).js"
    - "src/assets/js/main.js"
